export const drivers = {
  loading: false,
  success: true,
  drivers: [
    {
      rank: 1,
      points: 25,
      firstname: 'Max',
      lastname: 'Verstappen',
      abbr: null,
    },
    {
      rank: 2,
      points: 18,
      firstname: 'Sergio',
      lastname: 'Perez',
      abbr: null,
    },
    {
      rank: 3,
      points: 15,
      firstname: 'Fernando',
      lastname: 'Alonso',
      abbr: null,
    },
    {
      rank: 4,
      points: 12,
      firstname: 'Carlos',
      lastname: 'Sainz',
      abbr: null,
    },
    {
      rank: 5,
      points: 10,
      firstname: 'Lewis',
      lastname: 'Hamilton',
      abbr: null,
    },
    {
      rank: 6,
      points: 8,
      firstname: 'Lance',
      lastname: 'Stroll',
      abbr: null,
    },
    {
      rank: 7,
      points: 6,
      firstname: 'George',
      lastname: 'Russell',
      abbr: null,
    },
    {
      rank: 8,
      points: 4,
      firstname: 'Valtteri',
      lastname: 'Bottas',
      abbr: null,
    },
    {
      rank: 9,
      points: 2,
      firstname: 'Pierre',
      lastname: 'Gasly',
      abbr: null,
    },
    {
      rank: 10,
      points: 1,
      firstname: 'Alexander',
      lastname: 'Albon',
      abbr: null,
    },
    {
      rank: 11,
      points: 0,
      firstname: 'Yuki',
      lastname: 'Tsunoda',
      abbr: null,
    },
    {
      rank: 12,
      points: 0,
      firstname: 'Logan',
      lastname: 'Sargeant',
      abbr: null,
    },
    {
      rank: 13,
      points: 0,
      firstname: 'Kevin',
      lastname: 'Magnussen',
      abbr: null,
    },
    {
      rank: 14,
      points: 0,
      firstname: 'Nyck',
      lastname: 'De Vries',
      abbr: null,
    },
    {
      rank: 15,
      points: 0,
      firstname: 'Nico',
      lastname: 'Hulkenberg',
      abbr: null,
    },
    {
      rank: 16,
      points: 0,
      firstname: 'Guanyu',
      lastname: 'Zhou',
      abbr: null,
    },
    {
      rank: 17,
      points: 0,
      firstname: 'Lando',
      lastname: 'Norris',
      abbr: null,
    },
    {
      rank: 0,
      points: 0,
      firstname: 'Charles',
      lastname: 'Leclerc',
      abbr: null,
    },
    {
      rank: 0,
      points: 0,
      firstname: 'Esteban',
      lastname: 'Ocon',
      abbr: null,
    },
    {
      rank: 0,
      points: 0,
      firstname: 'Oscar',
      lastname: 'Piastri',
      abbr: null,
    },
  ],
  httpStatusCode: 200,
};

export const driverDetails = {
  loading: false,
  success: true,
  driverDetails: {
    team: 'Red Bull Racing',
    country: 'Netherlands',
    podiums: '78',
    points: '2036.5',
    grandsPrixEntered: '164',
    worldChampionships: '2',
    highestRaceFinish: '1 (x36)',
    highestGridPosition: '1',
    dateOfBirth: '30/09/1997',
    placeOfBirth: 'Hasselt, Belgium',
    firstname: 'Max',
    lastname: 'Verstappen',
    abbr: null,
  },
  httpStatusCode: 200,
};
