export const raceResult = {
  loading: false,
  success: true,
  raceResultsFiltered: [
    {
      pos: '1',
      no: '1',
      driver: 'Max Verstappen VER',
      car: 'Red Bull Racing Honda RBPT',
      laps: '57',
      time_Retired: '1:33:56.736',
      pts: 25,
    },
    {
      pos: '2',
      no: '11',
      driver: 'Sergio Perez PER',
      car: 'Red Bull Racing Honda RBPT',
      laps: '57',
      time_Retired: '+11.987s',
      pts: 18,
    },
    {
      pos: '3',
      no: '14',
      driver: 'Fernando Alonso ALO',
      car: 'Aston Martin Aramco Mercedes',
      laps: '57',
      time_Retired: '+38.637s',
      pts: 15,
    },
    {
      pos: '4',
      no: '55',
      driver: 'Carlos Sainz SAI',
      car: 'Ferrari',
      laps: '57',
      time_Retired: '+48.052s',
      pts: 12,
    },
    {
      pos: '5',
      no: '44',
      driver: 'Lewis Hamilton HAM',
      car: 'Mercedes',
      laps: '57',
      time_Retired: '+50.977s',
      pts: 10,
    },
    {
      pos: '6',
      no: '18',
      driver: 'Lance Stroll STR',
      car: 'Aston Martin Aramco Mercedes',
      laps: '57',
      time_Retired: '+54.502s',
      pts: 8,
    },
    {
      pos: '7',
      no: '63',
      driver: 'George Russell RUS',
      car: 'Mercedes',
      laps: '57',
      time_Retired: '+55.873s',
      pts: 6,
    },
    {
      pos: '8',
      no: '77',
      driver: 'Valtteri Bottas BOT',
      car: 'Alfa Romeo Ferrari',
      laps: '57',
      time_Retired: '+72.647s',
      pts: 4,
    },
    {
      pos: '9',
      no: '10',
      driver: 'Pierre Gasly GAS',
      car: 'Alpine Renault',
      laps: '57',
      time_Retired: '+73.753s',
      pts: 2,
    },
    {
      pos: '10',
      no: '23',
      driver: 'Alexander Albon ALB',
      car: 'Williams Mercedes',
      laps: '57',
      time_Retired: '+89.774s',
      pts: 1,
    },
    {
      pos: '11',
      no: '22',
      driver: 'Yuki Tsunoda TSU',
      car: 'AlphaTauri Honda RBPT',
      laps: '57',
      time_Retired: '+90.870s',
      pts: 0,
    },
    {
      pos: '12',
      no: '2',
      driver: 'Logan Sargeant SAR',
      car: 'Williams Mercedes',
      laps: '56',
      time_Retired: '+1 lap',
      pts: 0,
    },
    {
      pos: '13',
      no: '20',
      driver: 'Kevin Magnussen MAG',
      car: 'Haas Ferrari',
      laps: '56',
      time_Retired: '+1 lap',
      pts: 0,
    },
    {
      pos: '14',
      no: '21',
      driver: 'Nyck De Vries DEV',
      car: 'AlphaTauri Honda RBPT',
      laps: '56',
      time_Retired: '+1 lap',
      pts: 0,
    },
    {
      pos: '15',
      no: '27',
      driver: 'Nico Hulkenberg HUL',
      car: 'Haas Ferrari',
      laps: '56',
      time_Retired: '+1 lap',
      pts: 0,
    },
    {
      pos: '16',
      no: '24',
      driver: 'Zhou Guanyu ZHO',
      car: 'Alfa Romeo Ferrari',
      laps: '56',
      time_Retired: '+1 lap',
      pts: 0,
    },
    {
      pos: '17',
      no: '4',
      driver: 'Lando Norris NOR',
      car: 'McLaren Mercedes',
      laps: '55',
      time_Retired: '+2 laps',
      pts: 0,
    },
    {
      pos: 'NC',
      no: '31',
      driver: 'Esteban Ocon OCO',
      car: 'Alpine Renault',
      laps: '41',
      time_Retired: 'DNF',
      pts: 0,
    },
    {
      pos: 'NC',
      no: '16',
      driver: 'Charles Leclerc LEC',
      car: 'Ferrari',
      laps: '39',
      time_Retired: 'DNF',
      pts: 0,
    },
    {
      pos: 'NC',
      no: '81',
      driver: 'Oscar Piastri PIA',
      car: 'McLaren Mercedes',
      laps: '13',
      time_Retired: 'DNF',
      pts: 0,
    },
  ],
  title: 'FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2023 - RACE RESULT',
  raceDate: '05 Mar 2023',
  location: 'Bahrain International Circuit, Sakhir',
  httpStatusCode: 200,
};
