export const DRIVERS_REQUEST = 'DRIVERS_REQUEST';
export const DRIVERS_SUCCESS = 'DRIVERS_SUCCESS';
export const DRIVERS_FAILURE = 'DRIVERS_FAILURE';

export const DRIVER_DETAILS_REQUEST = 'DRIVER_DETAILS_REQUEST';
export const DRIVER_DETAILS_SUCCESS = 'DRIVER_DETAILS_SUCCESS';
export const DRIVER_DETAILS_FAILURE = 'DRIVER_DETAILS_FAILURE';
